/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokemonTableRouteImport } from './routes/pokemon-table'
import { Route as FormRouteImport } from './routes/form'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokemonIdRouteImport } from './routes/pokemon.$id'

const PokemonTableRoute = PokemonTableRouteImport.update({
  id: '/pokemon-table',
  path: '/pokemon-table',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIdRoute = PokemonIdRouteImport.update({
  id: '/pokemon/$id',
  path: '/pokemon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/pokemon-table': typeof PokemonTableRoute
  '/pokemon/$id': typeof PokemonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/pokemon-table': typeof PokemonTableRoute
  '/pokemon/$id': typeof PokemonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/pokemon-table': typeof PokemonTableRoute
  '/pokemon/$id': typeof PokemonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/pokemon-table' | '/pokemon/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/pokemon-table' | '/pokemon/$id'
  id: '__root__' | '/' | '/form' | '/pokemon-table' | '/pokemon/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormRoute: typeof FormRoute
  PokemonTableRoute: typeof PokemonTableRoute
  PokemonIdRoute: typeof PokemonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pokemon-table': {
      id: '/pokemon-table'
      path: '/pokemon-table'
      fullPath: '/pokemon-table'
      preLoaderRoute: typeof PokemonTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$id': {
      id: '/pokemon/$id'
      path: '/pokemon/$id'
      fullPath: '/pokemon/$id'
      preLoaderRoute: typeof PokemonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormRoute: FormRoute,
  PokemonTableRoute: PokemonTableRoute,
  PokemonIdRoute: PokemonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
